name: flutter_horizontal_date_picker
description: A Flutter package to create a Horizontal Date Picker. It will be useful for your awesome app.
version: 1.1.1
homepage: https://romanticdeveloper.com
repository: https://github.com/minhhung2556/romantic_project_flutter_horizontal_date_picker

environment:
  sdk: '>=2.12.0 <=3.5.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
